name: "ItemMailPlugin"
version: "1.0"
main: "tororo1066.itemmail.ItemMailPlugin"
api-version: "1.20"
loader: tororo1066.itemmail.DependencyLoader

dependencies:
  server:
    NMSUtils:
      load: BEFORE